# Site settings
title: Ali Robertson 
email: ali@ali.id.au
description: System Architect & Tech Strategist. Helping organisations find a clear path through their information management & software development journeys.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.ali.id.au" # the base hostname & protocol for your site
twitter_username: alirobe
github_username:  alirobe

# Build settings
markdown: kramdown
permalink: pretty
timezone: Australia/Melbourne
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: "pages"
    values:
      layout: page