baseURL = "https://www.ali.id.au/"
languageCode = "en-au"
title = "Ali Robertson"

# Disable taxonomy pages
disableKinds = ["taxonomy", "term"]

# Enable robots.txt generation
enableRobotsTXT = true

[params]
  description = "Melbourne-based technical architect and developer specialising in Microsoft 365, Dynamics 365, and Power Platform. Helping organisations find a clear path through their Microsoft tech."
  author = "Ali Robertson"
  email = "ali@ali.id.au"
  twitter_username = "alirobe"
  github_username = "alirobe"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  page = "/:sections[last]/"

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
